### ISSUE TITLE
How to build this project?

### ISSUE THREAD

**Issue by RexYuan** [chipsalliance/tilelink#16]
I successfully compiled `tests.elaborate` by adding this just above `upstreamCompileOutput()`
```scala
def finalMainClass () = "tests.elaborate.Main"
```

But for `mfccompile` I'm stuck at this part
```bash
> mill tests.mfccompile.compile
[8/265] foreign-modules.dependencies.firrtl.build.firrtlCrossModule.sources.overridden.mill.scalalib.SbtM
[53/265] foreign-modules.dependencies.chisel3.build.chisel3CrossModule.macros.sources.overridden.mill.sca
[85/265] foreign-modules.dependencies.chisel3.build.chisel3CrossModule.core.sources.overridden.mill.scala
[121/265] foreign-modules.dependencies.chisel3.build.chisel3CrossModule.sources.overridden.mill.scalalib.
[151/265] foreign-modules.dependencies.chisel3.build.chisel3CrossModule.plugin.sources.overridden.mill.sc
[262/265] tests.elaborate.elaborate 
java.nio.file.NoSuchFileException: /Users/rexyuan/Sources/tilelink/config.json
        at ... ()
        at os.Path.getInputStream(Path.scala:491)
        at os.read$bytes$.apply(ReadWriteOps.scala:256)
        at os.read$.apply(ReadWriteOps.scala:216)
        at os.read$.apply(ReadWriteOps.scala:214)
        at tests.elaborate.Main$.$anonfun$TLCrossBar$1(Main.scala:31)
        at ... ()
        at ... (Stack trace trimmed to user code only. Rerun with --full-stacktrace to see the full stack trace)
```

What is this `config.json` file and what should I put in it?

**Comment by BenjaminSchlaich** [comment]
I'm also stuck trying to build the project. I would really appreciate it if you could add a little section to the Readme, explaining how to compile the tests. Thank you already!

**Comment by BenjaminSchlaich** [comment]
I successfully built the tests now with the following fixes:

1. Run "mill tests.elaborate.runMain tests.elaborate.TLCrossBarParameterSerializerTest". This will generate the config.json file which describes the TileLink architecture that is to be connected through the Crossbar.
2. Run "mill tests.elaborate.elaborate" and then "mill tests.mfccompile.compile" to generate the SystemVerilog files according to that configuration.
3. Use firtool version 1.30.0 (can be found here https://github.com/llvm/circt/releases/tag/firtool-1.30.0). This worked for me, whereas other versions failed because of numerous problems.
